name: Update formula

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch latest version
        id: latest-version
        uses: octokit/graphql-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query {
              vim: repository(owner:"vim", name:"vim") {
                refs(refPrefix:"refs/tags/", last:1) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
            }

      - name: Check version format
        run: |
          latest=${{ fromJSON(steps.latest-version.outputs.data).vim.refs.edges[0].node.name }}
          [[ ${latest} =~ ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]

      - name: Update formula
        run: |
          latest=${{ fromJSON(steps.latest-version.outputs.data).vim.refs.edges[0].node.name }}
          sed -i '/^  url /s/:tag => "v[^"]*"/:tag => "'"${latest}"'"/' vim.rb
          if ! git diff --exit-code vim.rb; then
            git config --local user.name 'github-actions[bot]'
            git config --local user.email 'github-actions[bot]@users.noreply.github.com'
            git add vim.rb
            git commit -m "vim: ${latest#v}"
            git push -u origin master
          fi
